### ISSUE TITLE
Do NUL bytes have to be escaped?

### ISSUE THREAD

**Issue by nikic** [benjamingr/RegExp.escape#18]
Some regex flavors (like PCRE) truncate on NUL bytes, so languages using those also escape NUL bytes to `\000` or similar. Are JS regexes guaranteed to be binary safe, thus making this unnecessary?

**Comment by ljharb** [comment]
`var a = new RegExp('a\0b'); [a.test('ab'), a.test('a\0b')]` appears to work fine, and gives `[false, true]`.

**Comment by benjamingr** [comment]
Thanks for the question and also for teaching me about this behavior in PCRE.

JavaScript's regular expressions, assuming I understand the ES6 specification correctly do not exhibit this behavior.
