### ISSUE TITLE
Escape `-`?

### ISSUE THREAD

**Issue by benjamingr** [benjamingr/RegExp.escape#28]
Currently the proposal escapes `]` and `}` which isn't really required since we escape `[` and `{`. The only reason we might need to escape `]` is because we need to support the case that the pattern is inserted inside the `[`.

A preliminary GH code search shows that this pattern is actually used. In particular, underscore's string model does `"[" + escapedRegExp +"]`.

So, in my opinion we should support escaping inside matched sets to be on the safe side, this is somewhat wasteful (because there are other characters that do not need to be escaped in sets but the pattern is very common.

Opinions?

**Comment by benjamingr** [comment]
Also related, discussion in https://github.com/benjamingr/RegExp.escape/issues/17

**Comment by ljharb** [comment]
I don't think there's any concern with over-escaping here. The important thing `RegExp.escape` provides is a safety guarantee - not a performance guarantee.

Escaping every single character might be a bit extreme, but certainly escaping the ones that might be problematic in some cases doesn't seem to be.

**Comment by domenic** [comment]
Maybe what we want is a table in the readme with each escaped character and a reason why it's escaped (preferably in the form `new RegExp(something + RegExp.escape("the character") + something)` or some subset thereof)

**Comment by benjamingr** [comment]
@domenic  good idea, I'll make one soon.

@ljharb well, the most obvious reason is the readability impact, but I agree this is a use case we want to address.

**Comment by nikic** [comment]
Context:
* [`rtrim`](https://github.com/epeli/underscore.string/blob/71c49d6b9e44567f997b9e11d7a1d748a71040d6/rtrim.js)
* calls [`defaultToWhitespace`](https://github.com/epeli/underscore.string/blob/71c49d6b9e44567f997b9e11d7a1d748a71040d6/helper/defaultToWhiteSpace.js)
* calls [`escapeRegExp`](https://github.com/epeli/underscore.string/blob/71c49d6b9e44567f997b9e11d7a1d748a71040d6/helper/escapeRegExp.js)
* which escapes `.*+?^=!:${}()|[\]\/\\`

Note that this does *not* include `-`, as underscore presumably wants to allow you to write something like `trim("a-zA-Z0-9")` to trim all alphanumerics.

I suspect that this might be the cases in many places where something is inserted into `[]` and as such having `-` escaped there might not really be what you want.

**Comment by benjamingr** [comment]
Yes, but if you _want_ `-` to work as part of a group then `escape` is not
what you're after anyway. You want to be able to use a user input string or
a regular string literally. You can always just concat the string as a
regular expression and not call `.escape`

**Comment by benjamingr** [comment]
Superseding this with https://github.com/benjamingr/RegExp.escape/issues/29
