### ISSUE TITLE
Prepare me for presenting this to TC39

### ISSUE THREAD

**Issue by domenic** [benjamingr/RegExp.escape#32]
I'd like a list of what should be presented to TC39. Maybe even a quick slid.es deck or something. Here's my initial set of questions that I have:

- What issues need TC39's input, and could feasibly be decided in a final manner at the meeting? Versus, which are still open for general discussion?
- Is the API final, or is it going to grow some second parameter?
- What stage do you think is appropriate to ask for? 0, 1, or maybe 2?
- Please do https://github.com/benjamingr/RegExp.escape/issues/31

**Comment by benjamingr** [comment]
I'll make a deck. When do you need this by? If this could wait a few more days until the discussion at https://github.com/benjamingr/RegExp.escape/issues/29 has exhausted itself that'd be better but I can make one now.

Basically I'd like us to present 3 alternatives to the TC:

 - A minimalist escaped set producing readable input.
 - An extended (and safe) escaped set.
 - An extended (but less so) escaped set with a second RegExp parameter for escaping additional characters.

I'll make a list of pros and cons and use cases for each and a specification draft for each. In addition I'd like the TC to consider https://github.com/benjamingr/RegExp.escape/issues/27

I don't understand the stages as well as you but I think that if the TC can decide on which alternative we go forward with - there are no remaining action items.

Would making a list of people with domain knowledge who've read through this proposal and LGTM'd and commented be interesting?

**Comment by domenic** [comment]
> I'll make a deck. When do you need this by? If this could wait a few more days until the discussion at #29 has exhausted itself that'd be better but I can make one now.

There's plenty of time; a week before the meeting (July 28) would be fine.

> Basically I'd like us to present 3 alternatives to the TC:

That sounds pretty good.

> I don't understand the stages as well as you but I think that if the TC can decide on which alternative we go forward with - there are no remaining action items.

Besides deciding between the 3 alternatives, you mean?

> Would making a list of people with domain knowledge who've read through this proposal and LGTM'd and commented be interesting?

Yeah, I guess, although appeal to authority is meh---their comments would be the more interesting part.

**Comment by benjamingr** [comment]
> Besides deciding between the 3 alternatives, you mean?

Yes, if the TC can decides on which alternative we go with, and on allowing
implementations to expand the escape set there will be no more remaining
action items.

I agree about appeal to authority.

**Comment by benjamingr** [comment]
I tried to keep it short @domenic  http://slides.com/benjamingruenbaum/regexp-escape/live what do you think?

**Comment by bergus** [comment]
Minor quibble: "*Also escapes whitespace and `/`s so `eval` can be used on a RegExp.*" should read "*Also escapes whitespaces and `/`s so `eval` can be used on a `RegExp.escape`d string.*". As we figured out, `eval` being usable on a `RegExp` object relies on proper `toString` behaviour.

**Comment by benjamingr** [comment]
> As we figured out, eval being usable on a RegExp object relies on proper toString behaviour. 

Why?

**Comment by bergus** [comment]
You had [figured this out](https://github.com/benjamingr/RegExp.escape/issues/30#issuecomment-116555439) yourself in #30 :-) `eval(new RegExp(RegExp.escape(…)))` does work out of the box (because `.toString()` does the escaping of slashes and whitespace), the only concern was about `eval("/"+RegExp.escape(…)+"/")` for the "extended safe proposal" (plus readability of whitespaces might be better if not broken into multiple lines in debugging and logs).

You may credit me as "A. Bergmaier" if you wish. Still trying to keep a low profile :-)

**Comment by domenic** [comment]
@benjamingr looks pretty good. Is there any way I can get edit access? I just want to fix a couple typos and rearrange a couple slides.

**Comment by benjamingr** [comment]
Sure, I'll get home and invite you to edit

**Comment by benjamingr** [comment]
It doesn't look like there is a sane way to collaboratively edit a
slideshow on slides.com and it doesn't look like it can be exported to
css/html/js reveal code. Can you duplicate it and edit from your account?
