### ISSUE TITLE
Alternate proposal: RegExp.fromString

### ISSUE THREAD

**Issue by domenic** [benjamingr/RegExp.escape#33]
Instead of `new RegExp(RegExp.escape(s))`, you do `RegExp.fromString(s)`.

Pros:

- Shorter
- Escaping is simpler since we don't worry about cases like `new RegExp(s1 + RegExp.escape(s2) + s3)`

Cons:

- Maybe doesn't meet some important use cases?
- Do other languages do this? They all do escape...

**Comment by ljharb** [comment]
That's very interesting - presumably `RegExp.fromString` would accept an optional second "flags" argument. The only use cases I can come up with that it wouldn't meet involve concatenation.

**Comment by domenic** [comment]
Yep. The question is, what are the use cases involving concatenation, and does RegExp.escape properly meet them anyway? A lot of the discussion about the escape set seems focused around dubiously-valuable concatenation use cases.

**Comment by ljharb** [comment]
The ones that leap to my mind are:
 - concatenating with `^` and/or `$`, as part of a `startsWith`/`endsWith` semantic
 - surrounding it in parens to use it as a capturing group (negative and positive, lookbehind and lookahead) as part of a larger regexp

I think if I wanted to concatenate it with anything else, even some of the potentially problematic character patterns, i'd wrap it with `(?:` … `)` to ensure that it's a complete unit, which even in the `escape` situation seems like it would eliminate most of the edge cases.

Hopefully others can contribute their use cases as well :-)

**Comment by medikoo** [comment]
Name `fromString` suggests it is no different from `new RegExp(str)`, as it's how currently we create regular expressions _from strings_.
While `escape` is hard to be mistaken on its purpose, and it's also a first name most devs search when looking for RegExp _escape_ function.

Additionally I never seen a use case for: `RegExp(RegExp.escape(str))`, but met a lot of for: `RegExp('startRe' + RegExp.escape(str) + 'endRe )`

**Comment by domenic** [comment]
I don't care about the name. @ljharb those are quite helpful use case counterpoints!

**Comment by nikic** [comment]
Maybe I'm missing something here, but why would you ever want to create a regex that just matches a given string, without concatenating any additional requirements? If you only need to find a particular string, you can just use `indexOf`.

**Comment by domenic** [comment]
@nikic `str1.replace(str2, str3)` breaks because it converts `str2` to a RegExp (and a non-global one at that). You instead want `str1.replace(RegExp.fromString(str2, "g"), str3)`, or `str1.replace(new RegExp(RegExp.escape(str2), "g"), str3)`.

That is the only time I've ever needed `RegExp.escape`.

**Comment by nikic** [comment]
@domenic Thanks, I didn't know that JS doesn't support global string replacements. However if that's the actual use case here, then maybe shift one further from `str.replace(RegExp.fromString(str2, "g"), str3)` to `str.replaceAll(str2, str3)`?

Example for concat use case: Routes have literal and placeholder parts, the placeholders are regular expressions, while the literal parts need to be escaped.

**Comment by benjamingr** [comment]
- A very common use case for `.escape` is for example to search in a text - for example `".*" + escaped +".*"` or surrounded with word boundaries. 
 - Routes as @nikic pointed out are another common target where people shim `.escape` semantics.

I'm self assigning to make a list of pros/cons of this approach before the TC meeting.

**Comment by cscott** [comment]
I would like this approach, if introduced in connection with `Regexp.prototype.{alt|cat|mult|group}` combinators to safely combine regular expressions.  Then you could safely write:
```js
var re = /^/.cat(RegExp.fromString("foo")).alt(/bar$/); // equiv to: /(?:^foo)|bar/
```
Combinator methods for regexps are safer than the string operations folks mostly want to use RegExp.escape for.

But you'd also want something like `RegExp.characterClass(chars)`.  The current proposal lets you write that as `RegExp("[" + RegExp.escape(chars, /-/) + "]")`.

**Comment by domenic** [comment]
No, that doesn't make sense, as e.g. `/^/` is not a valid RegExp.

> The current proposal lets you write that as `RegExp("[" + RegExp.escape(chars, /-/) + "]")`.

That is not true. [The current proposal](http://benjamingr.github.io/RegExp.escape/) does not include a second parameter.

---

The concatenation use cases in this thread have been convincing enough to drop this idea. However, I will leave it open for @benjamingr to mine those use cases into something belonging in the readme.

**Comment by tiansh** [comment]
I like this proposal. Someone say they want operate on the result of `Regex.espace`, such as connect, group, ect. But these operation should be done between two RegExp instead of two String which should be done by another (group of) interface(s) / proposal , at least in my mind. It is hard to understand such operations on String instead of RegExp.

Maybe the name `fromString` is ambiguous, but any name is ok, such as `literal` (maybe I'm not good at this) ...

By the way, why `/^/` is invalid? If so, what about `/^(?:)/`, or even `/(?:)/` ?

I'm not sure where to post these, hopes not disturbing you.

**Comment by benjamingr** [comment]
@tiansh on esdiscuss http://esdiscuss.org https://mail.mozilla.org/listinfo/es-discuss
