### ISSUE TITLE
Explore other solutions

### ISSUE THREAD

**Issue by bergus** [benjamingr/RegExp.escape#38]
So, [the results are in](37), and it seems they declined `RegExp.escape` and this is a final decision.

What alternatives do we have? Of course we could just fall back on a user-land implementation (like [ljharb/regexp.escape](https://github.com/ljharb/regexp.escape), are there others?) as mentioned, but what if we want to press on?

* `RegExp.fromString`, #33, with regex combinators as `RegExp.prototype` methods, to provide a fluent interface for regex construction/combination
* `RegExp.tag`, for template strings, avoids double-escaping by accessing the `.raw` template parts, and solves the problem with trailing backslashes ([example](http://babeljs.io/repl/#?experimental=false&evaluate=true&loose=true&spec=false&playground=true&code=function%20escape(str)%20%7B%0A%20%20return%20str.replace(%2F%5B%5E%5D%2Fg%2C%20%22%5C%5C%24%26%22)%3B%20%2F%2F%20just%20everything%20for%20simplicity%0A%7D%0Afunction%20regex(parts%2C%20...values)%7B%0A%20%20var%20res%20%3D%20parts.raw%5B0%5D%3B%0A%20%20for%20(let%20i%3D1%3B%20i%3Cparts.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20res%20%2B%3D%20escape(arguments%5Bi%5D)%3B%0A%20%20%20%20res%20%2B%3D%20parts.raw%5Bi%5D%3B%0A%20%20%7D%0A%20%20return%20new%20RegExp(res)%3B%0A%7D%0Aconsole.log(regex%60%5Cw%20yi%24%24%7B%22%7C%5C%5C%22%7D%7B2%7Dkes%0A%5Cn%60.source)))

Both do have a problem with flags though, which are difficult to express. Is there anything else?

**Comment by bergus** [comment]
The first thing to do is probably to find a reasonable name for `RegExp.tag` (`tag` is horrible) before it settles in our minds.

**Comment by benjamingr** [comment]
`RegExp.escaped` but I don't feel like a tag is the "right" way to go forward yet.

**Comment by bergus** [comment]
Oh, and judging from the discussion in #37 there seems to be confusion on what such a tagging function would return. Everyone seems to expect a string (that needs then be passed into the `RegExp` constructor, but I would propose it to return a regex instance? Or maybe a function that takes the flags as an argument, so that we could write something like

     RegExp.… `\s*${input}\s*` ("ig")

**Comment by ljharb** [comment]
It should probably only return a RegExp instance, otherwise all of the same compositional problems will exist as do with `escape`.

Changing the flags is trivial by wrapping in the constructor: `RegExp(existingRegExp, newFlags)`

**Comment by erights** [comment]
I am pleased to bring https://github.com/mikesamuel/regexp-make-js to your attention. Mike Samuel and I (mostly Mike) put together this draft specification and prototype implementation for what the RegExp template string tag should be. We think this is a comprehensive and principled approach ready for examination and discussion. Would it be better to discuss this here on this thread, or over at https://github.com/mikesamuel/regexp-make-js ?

This prototype implementation currently uses some ES6 features that are directly implemented only on Firefox. After reading the README, I suggest reading the tests next while visiting https://rawgit.com/mikesamuel/regexp-make-js/master/test.html in a Firefox browser. I think the tests should quickly clear up most questions about what the draft spec means. Please point out any ambiguities that remain. Thanks!

**Comment by bergus** [comment]
@erights A new repository seems suited for discussion of this particular approach. As you can see, I've just opened 6 issues there :-)

**Comment by benjamingr** [comment]
@erights that proposal looks abandoned, status?
