### ISSUE TITLE
Alternative solutions

### ISSUE THREAD

**Issue by benjamingr** [benjamingr/RegExp.escape#4]
If anyone has any alternative to this solutions they think should be considered instead - this is the place to talk about it.

**Comment by domenic** [comment]
A template string tag merits discussion.

**Comment by benjamingr** [comment]
It does, I think that a future `Regex.join` as suggested [here](https://esdiscuss.org/topic/regexp-escape#content-22) that lets you stitch routes for example would be interesting:

    RegExp.join`Hello ${"..."}`

I think `.escape` is a lower level primitive and `join` and is simpler and could be easily built on top of it - so I tend to go for `escape`. Also `.escape` is:

 - a lot less work to implement.
 - polyfillable in ES5 and ES3 environments.
 - More similar to the use cases _I_ am familiar with where `.escape` is used on a single user provided string.

Use cases where a template solution provides a nicer API would be interesting

**Comment by domenic** [comment]
> I think .escape is a lower level primitive and join and is simpler and could be easily built on top of it

This is the strongest argument IMO.

> a lot less work to implement.

Exaggerating a bit; template tags are just functions, and this would be one with a few more lines and a loop.

> polyfillable in ES5 and ES3 environments.

I personally hate this argument (polyfills should not govern language evolution) but I think others will be sympathetic to it so it's a good one. That's how we got stuff like Map.prototype.forEach after all.

> Use cases where a template solution provides a nicer API would be interesting

Compare:

```js
const re = new RegExp("Stuff\\.\\n" + RegExp.escape(userInput) + "(\\r)?\\n");

const re2 = RegExp.join`Stuff\.\n${userInput}(\r)?\n`;
```

although I don't understand the join name.

**Comment by benjamingr** [comment]
I don't understand the join name either, I'd still call it `escape` if it
was a template tag function.

How would specifying flags look like with a template tag? Would it be
placed before the tag as in:

```
RegExp.join("g")`Stuff${userInput}`
```

?

**Comment by domenic** [comment]
Good question. Probably, yeah.

**Comment by domenic** [comment]
I'd call it `re` as in

```js
const re = RegExp.re;

const myRe = re`Stuff \d+\.\n${userInput}(\r)?\n`;
```

**Comment by domenic** [comment]
Maybe two functions, `RegExp.re` and `RegExp.re.withFlags("g")`

**Comment by benjamingr** [comment]
I don't see a way around making it a function that returns a function in order to support flags and I'm not a fan of that in the spec (there is no precedent I'm aware of).

**Comment by benjamingr** [comment]
There is a review of what every other language does in the meeting we've had today in https://github.com/benjamingr/RegExp.escape/blob/master/data/other_languages/discussions.md

**Comment by benjamingr** [comment]
I think it is established that a tag won't work - closing. Cheers and thanks.
