### ISSUE TITLE
Identification of potential “cross-cutting” concerns

### ISSUE THREAD

**Issue by benjamingr** [benjamingr/RegExp.escape#5]
As far as I'm aware `escape` does not interfere with any other APIs and uses the list of identifiers from the spec rather than define it to keep it in track. If anyone is able to identify interference this would be a good place to report it.

**Comment by domenic** [comment]
> uses the list of identifiers from the spec rather than define it to keep it in track

Worth noting this in the readme as a potential concern that you've taken care of.

**Comment by benjamingr** [comment]
Thanks, done.

**Comment by domenic** [comment]
I was thinking explicitly under a "cross-cutting concerns" section so it's obvious you've ticked off this box :)

**Comment by benjamingr** [comment]
Hah, sure - will do.
